skill_items[7] = [
    new SkillItem('Crayfish', 1, 30, ['Fishes']),
    new SkillItem('Cooked Rabbit', 1, 30, ['Meats']),
    new SkillItem('Gutting Fish', 1, 10, ['Other']),
    new SkillItem('Cooked Meat', 1, 30, ['Meats']),
    new SkillItem('Cooked Chicken', 1, 30, ['Meats']),
    new SkillItem('Karambwanji', 1, 10, ['Fishes']),
    new SkillItem('Shrimp', 1, 30, ['Fishes']),
    new SkillItem('Sq\'irk Juice', 1, 5, ['Other']),
    new SkillItem('Sardine', 1, 40, ['Fishes']),
    new SkillItem('Poorly Cooked Karambwan', 1, 80, ['Fishes']),
    new SkillItem('Anchovy', 1, 30, ['Fishes']),
    new SkillItem('Sinew', 3, 3, ['Other']),
    new SkillItem('Herring', 5, 50, ['Fishes']),
    new SkillItem('Baked Potato', 7, 15, ['Potatoes']),
    new SkillItem('Mackarel', 10, 60, ['Fishes']),
    new SkillItem('Redberry Pie', 10, 78, ['Pies']),
    new SkillItem('Roast Bird Meat', 11, 62.5, ['Meats']),
    new SkillItem('Thin Snail', 12, 70, ['Meats']),
    new SkillItem('Trout', 15, 70, ['Fishes']),
    new SkillItem('Roast Rabbit', 16, 72.5, ['Meats']),
    new SkillItem('Lean Snail', 17, 80, ['Meats']),
    new SkillItem('Cod', 18, 75, ['Fishes']),
    new SkillItem('Meat Pie', 20, 110, ['Pies']),
    new SkillItem('Crabmeat', 21, 100, ['Meats']),
    new SkillItem('Fat Snail', 22, 95, ['Meats']),
    new SkillItem('Stews', 25, 117, ['Stews']),
    new SkillItem('Spicy Stew', 25, 117, ['Stews']),
    new SkillItem('Salmon', 25, 90, ['Fishes']),
    new SkillItem('Slimey Eel', 28, 95, ['Fishes']),
    new SkillItem('Sweetcorn', 28, 104, ['Other']),
    new SkillItem('Mud Pie', 29, 128, ['Pies']),
    new SkillItem('Tuna', 30, 110, ['Fishes']),
    new SkillItem('Apple Pie', 30, 130, ['Pies']),
    new SkillItem('Chompy Bird Meat', 30, 140, ['Meats']),
    new SkillItem('Karambwan', 30, 190, ['Fishes']),
    new SkillItem('Fish Cake', 31, 100, ['Other']),
    new SkillItem('Garden Pie', 34, 138, ['Pies']),
    new SkillItem('Plain Pizza', 35, 143, ['Pizza']),
    new SkillItem('Rainbow Fish', 35, 110, ['Fishes']),
    new SkillItem('Wine', 35, 200, ['Other']),
    new SkillItem('Cave Eel', 38, 115, ['Fishes']),
    new SkillItem('Baked Potato with Butter', 39, 95.5, ['Potatoes']),
    new SkillItem('Lobster', 40, 120, ['Fishes']),
    new SkillItem('Cake', 40, 180, ['Cakes']),
    new SkillItem('Jubbly Bird Meat', 41, 160, ['Meats']),
    new SkillItem('Chilli Potato', 41, 165.5, ['Potatoes']),
    new SkillItem('Bass', 43, 130, ['Fishes']),
    new SkillItem('Meat Pizza', 45, 169, ['Pizza']),
    new SkillItem('Swordfish', 45, 140, ['Fishes']),
    new SkillItem('Fish Pie', 47, 164, ['Pies']),
    new SkillItem('Baked Potato with Cheese', 47, 199.5, ['Potatoes']),
    new SkillItem('Chocolate Cake', 50, 210, ['Cakes']),
    new SkillItem('Egg Potato', 51, 195.5, ['Potatoes']),
    new SkillItem('Lava Eel', 53, 30, ['Fishes']),
    new SkillItem('Anchovy Pizza', 55, 182, ['Pizza']),
    new SkillItem('Ugthanki Kebab', 58, 80, ['Other']),
    new SkillItem('Monkfish', 62, 150, ['Fishes']),
    new SkillItem('Mushroom Potato', 64, 270.5, ['Potatoes']),
    new SkillItem('Pineapple Pizza', 65, 188, ['Pizza']),
    new SkillItem('Tuna Potato', 68, 309.5, ['Potatoes']),
    new SkillItem('Admiral Pie', 70, 210, ['Pies']),
    new SkillItem('Shark', 80, 210, ['Fishes']),
    new SkillItem('Sea Turtle', 82, 211.3, ['Fishes']),
    new SkillItem('Wild Pie', 85, 240, ['Pies']),
    new SkillItem('Cavefish', 88, 214, ['Fishes']),
    new SkillItem('Manta Ray', 91, 216.3, ['Fishes']),
    new SkillItem('Rocktail', 93, 225, ['Fishes']),
    new SkillItem('Summer Pie', 95, 260, ['Pies']),
];