skill_info[12] = {
    name: 'Crafting',
    categories: {
        title: 'Category',
        values: ['Battlestaves', 'Glassblowing', 'Jewellery', 'Leather', 'Pottery', 'Silver', 'Spinning/Weaving', 'Other']
    },
    subcategories: {
        title: 'Experience',
        values: ['Partial', 'Total']
    },
    items: [
        new SkillItem('Ball of Wool', 1, 2.5, ['Spinning/Weaving']),
        new SkillItem('Beer Glass', 1, 17.5, ['Glassblowing', 'Partial']),
        new SkillItem('Beer Glass + Superglass', 1, 27.5, ['Glassblowing', 'Total']),
        new SkillItem('Beer Glass + Molten Glass', 1, 37.5, ['Glassblowing', 'Total']),
        new SkillItem('Cut Opal', 1, 15, ['Jewellery']),
        new SkillItem('Leather Gloves', 1, 13.8, ['Leather']),
        new SkillItem('Limestone Brick', 1, 6, ['Other']),
        new SkillItem('Molten Glass w/ Superglass Make', 1, 10, ['Glassblowing', 'Partial']),
        new SkillItem('Molten Glass', 1, 20, ['Glassblowing', 'Partial']),
        new SkillItem('Pot', 1, 12.6, ['Pottery']),
        new SkillItem('String Amulet', 1, 4, ['Jewellery']),
        new SkillItem('Fungal Visor', 3, 15, ['Leather']),
        new SkillItem('Candle Lantern', 4, 19, ['Glassblowing', 'Partial']),
        new SkillItem('Candle Lantern + Superglass', 4, 29, ['Glassblowing', 'Total']),
        new SkillItem('Candle Lantern + Molten Glass', 4, 39, ['Glassblowing', 'Total']),
        new SkillItem('Clay Ring', 4, 19.9, ['Pottery']),
        new SkillItem('Gold Ring', 5, 15, ['Jewellery']),
        new SkillItem('Gold Necklace', 6, 20, ['Jewellery']),
        new SkillItem('Gold Bracelet', 7, 25, ['Jewellery']),
        new SkillItem('Leather Boots', 7, 16.3, ['Leather']),
        new SkillItem('Pie Dish', 7, 25, ['Pottery']),
        new SkillItem('Bowl', 8, 33, ['Pottery']),
        new SkillItem('Gold Amulet', 8, 30, ['Jewellery']),
        new SkillItem('Leather Cowl', 9, 18.5, ['Leather']),
        new SkillItem('Bowstring', 10, 15, ['Spinning/Weaving']),
        new SkillItem('Crossbow String', 10, 15, ['Spinning/Weaving']),
        new SkillItem('Strip of Cloth', 10, 12, ['Spinning/Weaving']),
        new SkillItem('Leather Vambraces', 11, 22, ['Leather']),
        new SkillItem('Fungal Leggings', 12, 50, ['Leather']),
        new SkillItem('Oil Lamp', 12, 25, ['Glassblowing', 'Partial']),
        new SkillItem('Oil Lamp + Superglass', 12, 35, ['Glassblowing', 'Total']),
        new SkillItem('Oil Lamp + Molten Glass', 12, 45, ['Glassblowing', 'Total']),
        new SkillItem('Cut Jade', 13, 20, ['Jewellery']),
        new SkillItem('Leather Body', 14, 25, ['Leather']),
        new SkillItem('Snail Helmet', 15, 32.5, ['Other']),
        new SkillItem('Cut Red Topaz', 16, 25, ['Jewellery']),
        new SkillItem('Holy Symbol', 16, 50, ['Silver']),
        new SkillItem('Unholy Symbol', 17, 50, ['Silver']),
        new SkillItem('Leather Chaps', 18, 27, ['Leather']),
        new SkillItem('Silver Sickle', 18, 50, ['Silver']),
        new SkillItem('Magic String', 19, 30, ['Spinning/Weaving']),
        new SkillItem('Plant Pot', 19, 37.5, ['Pottery']),
        new SkillItem('Cut Sapphire', 20, 50, ['Jewellery', 'Partial']),
        new SkillItem('Sapphire Ring', 20, 40, ['Jewellery', 'Partial']),
        new SkillItem('Sapphire Ring + Cut Sapphire', 20, 90, ['Jewellery', 'Total']),
        new SkillItem('Fungal Poncho', 21, 125, ['Leather']),
        new SkillItem('Sack', 21, 38, ['Spinning/Weaving']),
        new SkillItem('Silver Crossbow Bolts', 21, 50, ['Silver']),
        new SkillItem('Sapphire Necklace', 22, 55, ['Jewellery', 'Partial']),
        new SkillItem('Sapphire Necklace + Cut Sapphire' , 22, 105, ['Jewellery', 'Total']),
        new SkillItem('Sapphire Bracelet', 23, 60, ['Jewellery', 'Partial']),
        new SkillItem('Sapphire Bracelet + Cut Sapphire', 23, 110, ['Jewellery', 'Total']),
        new SkillItem('Tiara', 23, 52.5, ['Silver']),
        new SkillItem('Sapphire Amulet', 24, 65, ['Jewellery', 'Partial']),
        new SkillItem('Sapphire Amulet + Cut Sapphire', 24, 115, ['Jewellery', 'Total']),
        new SkillItem('Pot Lid', 25, 40, ['Pottery']),
        new SkillItem('Oil Lantern', 26, 50, ['Glassblowing', 'Partial']),
        new SkillItem('Oil Lantern + Superglass', 26, 60, ['Glassblowing', 'Total']),
        new SkillItem('Oil Lantern + Molten Glass', 26, 70, ['Glassblowing', 'Total']),
        new SkillItem('Cut Emerald', 27, 67.5, ['Jewellery', 'Partial']),
        new SkillItem('Emerald Ring', 27, 55, ['Jewellery', 'Partial']),
        new SkillItem('Emerald Ring + Cut Emerald', 27, 122.5, ['Jewellery', 'Total']),
        new SkillItem('Hard Leather Body', 28, 35, ['Leather']),
        new SkillItem('Emerald Necklace', 29, 60, ['Jewellery', 'Partial']),
        new SkillItem('Emerald Necklace + Cut Emerald', 29, 127.5, ['Jewellery', 'Total']),
        new SkillItem('Emerald Bracelet', 30, 65, ['Jewellery', 'Partial']),
        new SkillItem('Emerald Bracelet + Cut Emerald', 30, 132.5, ['Jewellery', 'Total']),
        new SkillItem('Demonic Sigil', 30, 50, ['Silver']),
        new SkillItem('Rope', 30, 25, ['Spinning/Weaving']),
        new SkillItem('Emerald Amulet', 31, 70, ['Jewellery', 'Partial']),
        new SkillItem('Emerald Amulet + Cut Emerald', 31, 137.5, ['Jewellery', 'Total']),
        new SkillItem('Glass Vial', 33, 35, ['Glassblowing', 'Partial']),
        new SkillItem('Glass Vial + Superglass', 33, 45, ['Glassblowing', 'Total']),
        new SkillItem('Glass Vial + Molten Glass', 33, 55, ['Glassblowing', 'Total']),
        new SkillItem('Cut Ruby', 34, 85, ['Jewellery', 'Partial']),
        new SkillItem('Ruby Ring', 34, 70, ['Jewellery', 'Partial']),
        new SkillItem('Ruby Ring + Cut Ruby', 34, 155, ['Jewellery', 'Total']),
        new SkillItem('Basket', 36, 56, ['Spinning/Weaving']),
        new SkillItem('Coif', 38, 37, ['Leather']),
        new SkillItem('Ruby Necklace', 40, 75, ['Jewellery', 'Partial']),
        new SkillItem('Ruby Necklace + Cut Ruby', 40, 160, ['Jewellery', 'Total']),
        new SkillItem('Studded Body', 41, 40, ['Leather']),
        new SkillItem('Ruby Bracelet', 42, 80, ['Jewellery', 'Partial']),
        new SkillItem('Ruby Bracelet + Cut Ruby', 42, 165, ['Jewellery', 'Total']),
        new SkillItem('Fishbowl', 42, 42.5, ['Glassblowing', 'Partial']),
        new SkillItem('Fishbowl + Superglass', 42, 52.5, ['Glassblowing', 'Total']),
        new SkillItem('Fishbowl + Molten Glass', 42, 62.5, ['Glassblowing', 'Total']),
        new SkillItem('Cut Diamond', 43, 107.5, ['Jewellery', 'Partial']),
        new SkillItem('Diamond Ring', 43, 85, ['Jewellery', 'Partial']),
        new SkillItem('Diamond Ring + Cut Diamond', 43, 192.5, ['Jewellery', 'Total']),
        new SkillItem('Yak-hide Legs', 43, 32, ['Leather']),
        new SkillItem('Studded Leather Chaps', 44, 42, ['Leather']),
        new SkillItem('Snakeskin Boots', 45, 30, ['Leather']),
        new SkillItem('Glass Orb', 46, 52.5, ['Glassblowing', 'Partial']),
        new SkillItem('Glass Orb + Superglass', 46, 62.5, ['Glassblowing', 'Total']),
        new SkillItem('Glass Orb + Molten Glass', 46, 72.5, ['Glassblowing', 'Total']),
        new SkillItem('Yak-hide Body', 46, 32, ['Leather']),
        new SkillItem('Snakeskin Vambraces', 47, 35, ['Leather']),
        new SkillItem('Snakeskin Bandana', 48, 45, ['Leather']),
        new SkillItem('Bullseye Lantern Lens', 49, 55, ['Glassblowing', 'Partial']),
        new SkillItem('Bullseye Lantern Lens + Superglass', 49, 65, ['Glassblowing', 'Total']),
        new SkillItem('Bullseye Lantern Lens + Molten Glass', 49, 75, ['Glassblowing', 'Total']),
        new SkillItem('Ruby Amulet', 50, 85, ['Jewellery', 'Partial']),
        new SkillItem('Ruby Amulet + Cut Ruby', 50, 170, ['Jewellery', 'Total']),
        new SkillItem('Snakeskin Chaps', 51, 50, ['Leather']),
        new SkillItem('Snakeskin body', 53, 55, ['Leather']),
        new SkillItem('Water Battlestaff', 54, 100, ['Battlestaves', 'Partial']),
        new SkillItem('Water Battlestaff + Orb', 54, 152.5, ['Battlestaves', 'Partial']),
        new SkillItem('Water Battlestaff + Orb + Superglass', 54, 162.5, ['Battlestaves', 'Total']),
        new SkillItem('Water Battlestaff + Orb + Molten Glass', 54, 172.5, ['Battlestaves', 'Total']),
        new SkillItem('Cut Dragonstone', 55, 137.5, ['Jewellery', 'Partial']),
        new SkillItem('Dragonstone Ring', 55, 100, ['Jewellery', 'Partial']),
        new SkillItem('Dragonstone Ring + Cut Dragonstone', 55, 237.5, ['Jewellery', 'Total']),
        new SkillItem('Diamond Necklace', 56, 90, ['Jewellery', 'Partial']),
        new SkillItem('Diamond Necklace + Cut Diamond', 56, 197.5, ['Jewellery', 'Total']),
        new SkillItem('Green Dragonhide Vambraces', 57, 62, ['Leather']),
        new SkillItem('Diamond Bracelet', 58, 95, ['Jewellery', 'Partial']),
        new SkillItem('Diamond Bracelet + Cut Diamond', 58, 202.5, ['Jewellery', 'Total']),
        new SkillItem('Earth Battlestaff', 58, 112.5, ['Battlestaves', 'Partial']),
        new SkillItem('Earth Battlestaff + Orb', 58, 165, ['Battlestaves', 'Partial']),
        new SkillItem('Earth Battlestaff + Orb + Superglass', 58, 175, ['Battlestaves', 'Total']),
        new SkillItem('Earth Battlestaff + Orb + Molten Glass', 58, 185, ['Battlestaves', 'Total']),
        new SkillItem('Green Dragonhide Chaps', 60, 124, ['Leather']),
        new SkillItem('Fire Battlestaff', 62, 125, ['Battlestaves', 'Partial']),
        new SkillItem('Fire Battlestaff + Orb', 62, 177.5, ['Battlestaves', 'Partial']),
        new SkillItem('Fire Battlestaff + Orb + Superglass', 62, 187.5, ['Battlestaves', 'Total']),
        new SkillItem('Fire Battlestaff + Orb + Molten Glass', 62, 197.5, ['Battlestaves', 'Total']),
        new SkillItem('Green Dragonhide Body', 63, 186, ['Leather']),
        new SkillItem('Grifolic Visor', 65, 40, ['Leather']),
        new SkillItem('Air Battlestaff', 66, 137.5, ['Battlestaves', 'Partial']),
        new SkillItem('Air Battlestaff + Orb', 66, 190, ['Battlestaves', 'Partial']),
        new SkillItem('Air Battlestaff + Orb + Superglass', 66, 200, ['Battlestaves', 'Total']),
        new SkillItem('Air Battlestaff + Orb + Molten Glass', 66, 210, ['Battlestaves', 'Total']),
        new SkillItem('Blue Dragonhide Vambraces', 66, 70, ['Leather']),
        new SkillItem('Cut Onyx', 67, 167.5, ['Jewellery', 'Partial']),
        new SkillItem('Onyx Ring', 67, 115, ['Jewellery', 'Partial']),
        new SkillItem('Onyx Ring + Cut Onyx', 67, 282.5, ['Jewellery', 'Total']),
        new SkillItem('Blue Dragonhide Chaps', 68, 140, ['Leather']),
        new SkillItem('Diamond Amulet', 70, 100, ['Jewellery', 'Partial']),
        new SkillItem('Diamond Amulet + Cut Diamond', 70, 207.5, ['Jewellery', 'Total']),
        new SkillItem('Blue Dragonhide Body', 71, 210, ['Leather']),
        new SkillItem('Dragonstone Necklace', 72, 105, ['Jewellery', 'Partial']),
        new SkillItem('Dragonstone Necklace + Cut Dragonstone', 72, 242.5, ['Jewellery', 'Total']),
        new SkillItem('Grifolic Leggings', 72, 120, ['Leather']),
        new SkillItem('Red Dragonhide Vambraces', 73, 78, ['Leather']),
        new SkillItem('Dragonstone Bracelet', 74, 110, ['Jewellery', 'Partial']),
        new SkillItem('Dragonstone Bracelet + Cut Dragonstone', 74, 247.5, ['Jewellery', 'Total']),
        new SkillItem('Red Dragonhide Chaps', 75, 156, ['Leather']),
        new SkillItem('Ring of Slaying', 75, 15, ['Jewellery']),
        new SkillItem('Red Dragonhide Body', 77, 234, ['Leather']),
        new SkillItem('Grifolic Poncho', 78, 350, ['Leather']),
        new SkillItem('Black Dragonhide Vambraces', 79, 86, ['Leather']),
        new SkillItem('Feather Headdress', 79, 50, ['Other']),
        new SkillItem('Dragonstone Amulet', 80, 150, ['Jewellery', 'Partial']),
        new SkillItem('Dragonstone Amulet + Cut Dragonstone', 80, 287.5, ['Jewellery', 'Total']),
        new SkillItem('Black Dragonhide Chaps', 82, 172, ['Leather']),
        new SkillItem('Onyx Necklace', 82, 120, ['Jewellery', 'Partial']),
        new SkillItem('Onyx Necklace + Cut Onyx', 82, 287.5, ['Jewellery', 'Total']),
        new SkillItem('Black Dragonhide Body', 84, 258, ['Leather']),
        new SkillItem('Onyx Bracelet', 84, 125, ['Jewellery', 'Partial']),
        new SkillItem('Onyx Bracelet + Cut Onyx', 84, 292.5, ['Jewellery', 'Total']),
        new SkillItem('Ganodermic Visor', 86, 100, ['Leather']),
        new SkillItem('Light Orb', 87, 70, ['Glassblowing', 'Partial']),
        new SkillItem('Light Orb + Superglass', 87, 80, ['Glassblowing', 'Partial', 'Total']),
        new SkillItem('Light Orb + Molten Glass', 87, 90, ['Glassblowing', 'Partial', 'Total']),
        new SkillItem('Add Wire to Light Orb', 87, 104, ['Glassblowing', 'Partial']),
        new SkillItem('Light Orb + Wire', 87, 174, ['Glassblowing', 'Partial']),
        new SkillItem('Light Orb + Wire + Superglass', 87, 184, 'Glassblowing', 'Total'),
        new SkillItem('Light Orb + Wire + Molten Glass', 87, 194, ['Glassblowing', 'Total']),
        new SkillItem('Royal Dragonhide Vambraces', 87, 94, ['Leather']),
        new SkillItem('Potion Flask', 89, 100, ['Total']),
        new SkillItem('Royal Dragonhide Chaps', 89, 188, ['Leather']),
        new SkillItem('Onyx Amulet', 90, 165, ['Jewellery', 'Partial']),
        new SkillItem('Onyx Amulet + Cut Onyx', 90, 332.5, ['Jewellery', 'Total']),
        new SkillItem('Ganodermic Leggings', 92, 300, ['Leather']),
        new SkillItem('Royal Dragonhide Body', 93, 282, ['Leather']),
        new SkillItem('Ganodermic Poncho', 98, 1000, ['Leather']),
    ]
};
