skill_info[19] = {
    name: 'Farming',
    categories: {
        title: 'Category',
        values: ['Allotments', 'Bushes', 'Flowers', 'Herbs', 'Hops', 'Special', 'Fruit Trees', 'Normal Trees', 'Herblore Habitat', 'Other']
    },
    subcategories: {
        title: 'Experience',
        values: ['Planting', 'Picking', 'Checking', 'Total']
    },
    items: [
        // Allotments
        new SkillItem('Potatoes (Plant)',1, 8, ['Allotments', 'Planting']),
        new SkillItem('Potatoes (Pick)', 1, 9, ['Allotments', 'Picking']),
        new SkillItem('Onions (Plant)',5, 9.5, ['Allotments', 'Planting']),
        new SkillItem('Onions (Pick)', 5, 10.5, ['Allotments', 'Picking']),
        new SkillItem('Cabbage (Plant)', 7, 10, ['Allotments', 'Planting']),
        new SkillItem('Cabbage (Pick)', 7, 11.5, ['Allotments', 'Picking']),
        new SkillItem('Tomatoes (Plant)', 12, 12.5, ['Allotments', 'Planting']),
        new SkillItem('Tomatoes (Pick)', 12, 14, ['Allotments', 'Picking']),
        new SkillItem('Sweetcorn (Plant)', 20, 17, ['Allotments', 'Planting']),
        new SkillItem('Sweetcorn (Pick)', 20, 19, ['Allotments', 'Picking']),
        new SkillItem('Strawberries (Plant)', 31, 26, ['Allotments', 'Planting']),
        new SkillItem('Strawberries (Pick)', 31, 29, ['Allotments', 'Picking']),
        new SkillItem('Watermelon (Plant)', 47, 48.5, ['Allotments', 'Planting']),
        new SkillItem('Watermelon (Pick)', 47, 54.5, ['Allotments', 'Picking']),
        // Bushes
        new SkillItem('Redberries (Plant)', 10, 8.5, ['Bushes', 'Planting']),
        new SkillItem('Redberries (Pick)', 10, 4, ['Bushes', 'Picking']),
        new SkillItem('Redberries (Check)', 10, 64, ['Bushes', 'Checking']),
        new SkillItem('RedBerries (Plant + Check)', 10, 72.5, ['Bushes', 'Total']),
        new SkillItem('Jangerberries (Plant)', 48, 50.5, ['Bushes', 'Planting']),
        new SkillItem('Jangerberries (Pick)', 48, 19, ['Bushes', 'Picking']),
        new SkillItem('Jangerberries (Check)', 48, 284.5, ['Bushes', 'Checking']),
        new SkillItem('Jangerberries (Plant + Check)', 48, 335, ['Bushes', 'Total']),
        new SkillItem('Whiteberries (Plant)', 59, 78, ['Bushes', 'Planting']),
        new SkillItem('Whiteberries (Pick)', 59, 29, ['Bushes', 'Picking']),
        new SkillItem('Whiteberries (Check)', 59, 437, ['Bushes', 'Checking']),
        new SkillItem('Whiteberries (Plant + Check)', 59, 515, ['Bushes', 'Total']),
        new SkillItem('Poison Ivys (Plant)', 70, 120, ['Bushes', 'Planting']),
        new SkillItem('Poison Ivys (Pick)', 70, 45, ['Bushes', 'Picking']),
        new SkillItem('Poison Ivys (Check)', 70, 674, ['Bushes', 'Checking']),
        new SkillItem('Poison Ivys (Plant + Check)', 70, 794, ['Bushes', 'Total']),
        // Flowers
        new SkillItem('Marigold (Plant)', 2, 8.5, ['Flowers', 'Planting']),
        new SkillItem('Marigold (Pick)', 2, 47, ['Flowers', 'Picking']),
        new SkillItem('Rosemary (Plant)', 11, 12, ['Flowers', 'Planting']),
        new SkillItem('Rosemary (Pick)', 11, 66.5, ['Flowers', 'Picking']),
        new SkillItem('Nasturtium (Plant)', 24, 19.5, ['Flowers', 'Planting']),
        new SkillItem('Nasturtium (Pick)', 24, 111, ['Flowers', 'Picking']),
        new SkillItem('Woad (Plant)', 25, 20.5, ['Flowers', 'Planting']),
        new SkillItem('Woad (Pick)', 25, 111.5, ['Flowers', 'Picking']),
        new SkillItem('Limpwurt (Plant)', 26, 21.5, ['Flowers', 'Planting']),
        new SkillItem('Limpwurt (Pick)', 26, 120, ['Flowers', 'Picking']),
        new SkillItem('White Lily (Plant)', 52, 50, ['Flowers', 'Planting']),
        new SkillItem('White Lily (Pick)', 52, 250, ['Flowers', 'Picking']),
        // Herbs
        new SkillItem('Guam (Plant)', 9, 11, ['Herbs', 'Planting']),
        new SkillItem('Guam (Pick)', 9, 12.5, ['Herbs', 'Picking']),
        new SkillItem('Marrentill (Plant)', 14, 13.5, ['Herbs', 'Planting']),
        new SkillItem('Marrentill (Pick)', 14, 15, ['Herbs', 'Picking']),
        new SkillItem('Tarromin (Plant)', 19, 16, ['Herbs', 'Planting']),
        new SkillItem('Tarromin (Pick)', 19, 18, ['Herbs', 'Picking']),
        new SkillItem('Harralander (Plant)', 26, 21.5, ['Herbs', 'Planting']),
        new SkillItem('Harralander (Pick)', 26, 24, ['Herbs', 'Picking']),
        new SkillItem('Ranarr Weed (Plant)', 32, 27, ['Herbs', 'Planting']),
        new SkillItem('Ranarr Weed (Pick)', 32, 30.5, ['Herbs', 'Picking']),
        new SkillItem('Spirit Weed (Plant)', 36, 32, ['Herbs', 'Planting']),
        new SkillItem('Spirit Weed (Pick)', 36, 36, ['Herbs', 'Picking']),
        new SkillItem('Toadflax (Plant)', 38, 34, ['Herbs', 'Planting']),
        new SkillItem('Toadflax (Pick)', 38, 38.5, ['Herbs', 'Picking']),
        new SkillItem('Irit (Plant)', 44, 43, ['Herbs', 'Planting']),
        new SkillItem('Irit (Pick)', 44, 48.5, ['Herbs', 'Picking']),
        new SkillItem('Wergali (Plant)', 46, 52.8, ['Herbs', 'Planting']),
        new SkillItem('Wergali (Pick)', 46, 51.5, ['Herbs', 'Picking']),
        new SkillItem('Avantoe (Plant)', 50, 54.5, ['Herbs', 'Planting']),
        new SkillItem('Avantoe (Pick)', 50, 61.5, ['Herbs', 'Picking']),
        new SkillItem('Kwuarm (Plant)', 56, 69, ['Herbs', 'Planting']),
        new SkillItem('Kwuarm (Pick)', 56, 78, ['Herbs', 'Picking']),
        new SkillItem('Snapdragon (Plant)', 62, 87.5, ['Herbs', 'Planting']),
        new SkillItem('Snapdragon (Pick)', 62, 98.5, ['Herbs', 'Picking']),
        new SkillItem('Cadantine (Plant)', 67, 106.5, ['Herbs', 'Planting']),
        new SkillItem('Cadantine (Pick)', 67, 120, ['Herbs', 'Picking']),
        new SkillItem('Lantadyme (Plant)', 73, 134.5, ['Herbs', 'Planting']),
        new SkillItem('Lantadyme (Pick)', 73, 151.5, ['Herbs', 'Picking']),
        new SkillItem('Dwarf Weed (Plant)', 79, 170.5, ['Herbs', 'Planting']),
        new SkillItem('Dwarf Weed (Pick)', 79, 192, ['Herbs', 'Picking']),
        new SkillItem('Torstol (Plant)', 85, 199.5, ['Herbs', 'Planting']),
        new SkillItem('Torstol (Pick)', 85, 224.5, ['Herbs', 'Picking']),
        new SkillItem('Fellstalk (Plant)', 91, 225, ['Herbs', 'Planting']),
        new SkillItem('Fellstalk (Pick)', 91, 315.6, ['Herbs', 'Picking']),
        // Hops
        new SkillItem('Barley (Plant)', 3, 8.5, ['Hops', 'Planting']),
        new SkillItem('Barley (Pick)', 3, 9, ['Hops', 'Picking']),
        new SkillItem('Hammerstone (Plant)', 4, 9, ['Hops', 'Planting']),
        new SkillItem('Hammerstone (Pick)', 4, 10, ['Hops', 'Picking']),
        new SkillItem('Asgarnian (Plant)', 8, 11, ['Hops', 'Planting']),
        new SkillItem('Asgarnian (Pick)', 8, 12, ['Hops', 'Picking']),
        new SkillItem('Jutes (Plant)', 13, 13, ['Hops', 'Planting']),
        new SkillItem('Jutes (Pick)', 13, 14.5, ['Hops', 'Picking']),
        new SkillItem('Yanillian (Plant)', 16, 14.5, ['Hops', 'Planting']),
        new SkillItem('Yanillian (Pick)', 16, 16, ['Hops', 'Picking']),
        new SkillItem('Krandorian (Plant)', 21, 17.5, ['Hops', 'Planting']),
        new SkillItem('Krandorian (Pick)', 21, 19.5, ['Hops', 'Picking']),
        new SkillItem('Wildblood (Plant)', 28, 23, ['Hops', 'Planting']),
        new SkillItem('Wildblood (Pick)', 28, 26, ['Hops', 'Picking']),
        // Special
        new SkillItem('Evil Turnip (Plant)', 42, 41, ['Special', 'Planting']),
        new SkillItem('Evil Turnip (Pick)', 42, 46, ['Special', 'Picking']),
        new SkillItem('Mushroom (Plant)', 53, 61.5, ['Special', 'Planting']),
        new SkillItem('Mushroom (Pick)', 53, 57.6, ['Special', 'Picking']),
        new SkillItem('Cactus (Plant)', 55, 66.5, ['Special', 'Planting']),
        new SkillItem('Cactus Spine (Pick)', 55, 25, ['Special', 'Picking']),
        new SkillItem('Cactus (Check)', 55, 374, ['Special', 'Checking']),
        new SkillItem('Cactus (Plant + Check)', 55, 440.5, ['Special', 'Total']),
        new SkillItem('Belladonna (Plant)', 63, 91, ['Special', 'Planting']),
        new SkillItem('Nightshade (Pick)', 63, 512, ['Special', 'Picking']),
        new SkillItem('Calquat (Plant)', 72, 129.5, ['Special', 'Planting']),
        new SkillItem('Calquat (Pick)', 72, 48.5, ['Special', 'Picking']),
        new SkillItem('Calquat (Check)', 72, 12096, ['Special', 'Checking']),
        new SkillItem('Calquat (Plant + Check)', 72, 1225.5, ['Special', 'Total']),
        new SkillItem('Morchella Mushroom (Plant)', 74, 160, ['Special', 'Planting']),
        new SkillItem('Morchella Mushroom (Pick)', 74, 77.7, ['Special', 'Picking']),
        new SkillItem('Spirit Sapling (Plant)', 83, 199.5, ['Special', 'Planting']),
        new SkillItem('Spirit Tree (Check)', 83, 19301.8, ['Special', 'Checking']),
        new SkillItem('Spirit Tree (Plant + Check)', 83, 19501.3, ['Special', 'Total']),
        // Fruit Trees
        new SkillItem('Apple Tree (Plant)', 27, 22, ['Fruit Trees', 'Planting']),
        new SkillItem('Apple Tree (Check)', 27, 1199.5, ['Fruit Trees', 'Checking']),
        new SkillItem('Apple Tree (Pick 6)', 27, 51, ['Fruit Trees', 'Picking']),
        new SkillItem('Apple Tree (Plant + Check)', 27, 1221.5, ['Fruit Trees', 'Total']),
        new SkillItem('Apple Tree<br/>(Plant + Check + Pick 6)', 27, 1272.5, ['Fruit Trees', 'Total']),
        new SkillItem('Banana Tree (Plant)', 33, 28, ['Fruit Trees', 'Planting']),
        new SkillItem('Banana Tree (Check)', 33, 1750.5, ['Fruit Trees', 'Checking']),
        new SkillItem('Banana Tree (Pick 6)', 33, 63, ['Fruit Trees', 'Picking']),
        new SkillItem('Banana Tree (Plant + Check)', 33, 1778.5, ['Fruit Trees', 'Total']),
        new SkillItem('Banana Tree<br/>(Plant + Check + Pick 6)', 33, 1841.5, ['Fruit Trees', 'Total']),
        new SkillItem('Orange Tree (Plant)', 39, 35, ['Fruit Trees', 'Planting']),
        new SkillItem('Orange Tree (Check)', 39, 2470, ['Fruit Trees', 'Checking']),
        new SkillItem('Orange Tree (Plant + Check)', 39, 2505, ['Fruit Trees', 'Total']),
        new SkillItem('Orange Tree (Pick 6)', 39, 81, ['Fruit Trees', 'Picking']),
        new SkillItem('Orange Tree<br/>(Plant + Check + Pick 6)', 39, 2586, ['Fruit Trees', 'Total']),
        new SkillItem('Curry Tree (Plant)', 42, 40, ['Fruit Trees', 'Planting']),
        new SkillItem('Curry Tree (Check)', 42, 2907, ['Fruit Trees', 'Checking']),
        new SkillItem('Curry Tree (Pick 6)', 42, 90, ['Fruit Trees', 'Picking']),
        new SkillItem('Curry Tree (Plant + Check)', 42, 2947, ['Fruit Trees', 'Total']),
        new SkillItem('Curry Tree<br/>(Plant + Check + Pick 6)', 42, 3037, ['Fruit Trees', 'Total']),
        new SkillItem('Pineapple Plant (Plant)', 51, 57, ['Fruit Trees', 'Planting']),
        new SkillItem('Pineapple Plant (Check)', 51, 4605.7, ['Fruit Trees', 'Checking']),
        new SkillItem('Pineapple Plant (Pick 6)', 51, 129, ['Fruit Trees', 'Picking']),
        new SkillItem('Pineapple Plant (Plant + Check)', 51, 4662.7, ['Fruit Trees', 'Total']),
        new SkillItem('Pineapple<br/>Plant (Plant + Check + Pick 6)', 51, 4791.7, ['Fruit Trees', 'Total']),
        new SkillItem('Papaya Tree (Plant)', 57, 72, ['Fruit Trees', 'Planting']),
        new SkillItem('Papaya Tree (Check)', 57, 6146.4, ['Fruit Trees', 'Checking']),
        new SkillItem('Papaya Tree (Pick 6)', 57, 162, ['Fruit Trees', 'Picking']),
        new SkillItem('Papaya Tree (Plant + Check)', 57, 6218.4, ['Fruit Trees', 'Total']),
        new SkillItem('Papaya Tree<br/>(Plant + Check + Pick 6)', 57, 6380.4, ['Fruit Trees', 'Total']),
        new SkillItem('Palm Tree (Plant)', 68, 110.5, ['Fruit Trees', 'Planting']),
        new SkillItem('Palm Tree (Check)', 68, 10150.1, ['Fruit Trees', 'Checking']),
        new SkillItem('Palm Tree (Pick 6)', 68, 249, ['Fruit Trees', 'Picking']),
        new SkillItem('Palm Tree (Plant + Check)', 68, 10260.6, ['Fruit Trees', 'Total']),
        new SkillItem('Palm Tree<br/>(Plant + Check + Pick 6)', 68, 10509.6, ['Fruit Trees', 'Total']),
        // Normal Trees
        new SkillItem('Oak Sapling (Plant)', 15, 14, ['Normal Trees', 'Planting']),
        new SkillItem('Oak Tree (Check)', 15, 467.3, ['Normal Trees', 'Checking']),
        new SkillItem('Oak Tree (Plant + Check)', 15, 481.3, ['Normal Trees', 'Total']),
        new SkillItem('Willow Sapling (Plant)', 30, 25, ['Normal Trees', 'Planting']),
        new SkillItem('Willow Tree (Check)', 30, 1456.3, ['Normal Trees', 'Checking']),
        new SkillItem('Willow Tree (Plant + Check)', 30, 1481.3, ['Normal Trees', 'Total']),
        new SkillItem('Maple Sapling (Plant)', 45, 45, ['Normal Trees', 'Planting']),
        new SkillItem('Maple Tree (Check)', 45, 3403.4, ['Normal Trees', 'Checking']),
        new SkillItem('Maple Tree (Plant + Check)', 45, 3448.4, ['Normal Trees', 'Total']),
        new SkillItem('Yew Sapling (Plant)', 60, 81, ['Normal Trees', 'Planting']),
        new SkillItem('Yew Tree (Check)', 60, 7069.9, ['Normal Trees', 'Checking']),
        new SkillItem('Yew Tree (Plant + Check)', 60, 7150.9, ['Normal Trees', 'Total']),
        new SkillItem('Magic Sapling (Plant)', 75, 145.5, ['Normal Trees', 'Planting']),
        new SkillItem('Magic Tree (Check)', 75, 13768.5, ['Normal Trees', 'Checking']),
        new SkillItem('Magic Tree (Plant + Check)', 75, 13914, ['Normal Trees', 'Total']),
        // Herblore Habitat
        new SkillItem('Vine Flower (Plant)', 54, 52, ['Herblore Habitat', 'Planting']),
        new SkillItem('Vine Flower (Pick)', 54, 255, ['Herblore Habitat', 'Picking']),
        new SkillItem('Erzille (Plant)', 58, 52, ['Herblore Habitat', 'Planting']),
        new SkillItem('Erzille (Pick)', 58, 87, ['Herblore Habitat', 'Picking']),
        new SkillItem('Lergberry (Plant)', 61, 145.5, ['Herblore Habitat', 'Planting']),
        new SkillItem('Lergberry (Check)', 61, 236.3, ['Herblore Habitat', 'Checking']),
        new SkillItem('Lergberry (Pick)', 61, 31.5, ['Herblore Habitat', 'Picking']),
        new SkillItem('Argway (Plant)', 71, 110, ['Herblore Habitat', 'Planting']),
        new SkillItem('Argway (Pick)', 71, 125, ['Herblore Habitat', 'Picking']),
        new SkillItem('Ugune (Plant)', 74, 135, ['Herblore Habitat', 'Planting']),
        new SkillItem('Ugune (Pick)', 74, 152, ['Herblore Habitat', 'Picking']),
        new SkillItem('Shengo (Plant)', 76, 140.5, ['Herblore Habitat', 'Planting']),
        new SkillItem('Shengo (Pick)', 76, 160, ['Herblore Habitat', 'Picking']),
        new SkillItem('Kalferberry (Plant)', 77, 220.2, ['Herblore Habitat', 'Planting']),
        new SkillItem('Kalferberry (Check)', 77, 375.3, ['Herblore Habitat', 'Checking']),
        new SkillItem('Kalferberry (Pick)', 77, 52.5, ['Herblore Habitat', 'Picking']),
        new SkillItem('Samaden (Plant)', 80, 170, ['Herblore Habitat', 'Planting']),
        new SkillItem('Samaden (Pick)', 80, 190, ['Herblore Habitat', 'Picking']),
        // Other
        new SkillItem('Fill Compost Bucket', 1, 4.5, ['Other']),
        new SkillItem('Fill Super Compost Bucket', 1, 8.5, ['Other']),
        new SkillItem('Rake Weeds', 1, 4, ['Other']),
        new SkillItem('Treat Patch (Compost)', 1, 18, ['Other']),
        new SkillItem('Treat Patch (Super Compost)', 1, 26, ['Other']),
        new SkillItem('Pick Sorceress\'s Garden Herb', 1, 50, ['Other']),
        new SkillItem('Pick Winter Sq\'irk', 1, 30, ['Other']),
        new SkillItem('Pick Spring Sq\'irk', 1, 40, ['Other']),
        new SkillItem('Pick Autumn Sq\'irk', 1, 50, ['Other']),
        new SkillItem('Pick Summer Sq\'irk', 1, 60, ['Other']),
    ]
};
