skill_info[9] = {
    name: 'Fletching',
    categories: {
        title: 'Category',
        values: ['Bows', 'Arrows', 'Crossbow', 'Bolts', 'Darts', 'Other']
    },
    items: [
        new SkillItem('15 x Arrow Shaft (Normal)', 1, 5, ['Arrows']),
        new SkillItem('Headless Arrow', 1, 1.3, ['Arrows']),
        new SkillItem('Bronze Arrow', 1, 2.6, ['Arrows']),
        new SkillItem('Bronze Dart', 1, 1.8, ['Darts']),
        new SkillItem('Shortbow (Cut/String)', 1, 5, ['Bows']),
        new SkillItem('Shortbow', 1, 10, ['Bows']),
        new SkillItem('Bronze Bolt', 9, 0.5, ['Bolts']),
        new SkillItem('Bronze Crossbow Stock (Normal)', 9, 6, ['Crossbows']),
        new SkillItem('Bronze Crossbow', 9, 24, ['Crossbows']),
        new SkillItem('Opal Tipped Bolt', 11, 2.1, ['Bolts']),
        new SkillItem('20 x Arrow Shaft (Oak)', 15, 7.5, ['Arrows']),
        new SkillItem('Iron Arrow', 15, 3.8, ['Arrows']),
        new SkillItem('Oak Shortbow (Cut/String)', 20, 16.5, ['Bows']),
        new SkillItem('Oak Shortbow', 20, 33, ['Bows']),
        new SkillItem('Iron Dart', 22, 3.8, ['Darts']),
        new SkillItem('Bluerite Crossbow Stock (Oak)', 24, 16, ['Crossbows']),
        new SkillItem('Bluerite Crossbow', 24, 64, ['Crossbows']),
        new SkillItem('Jade Tipped Bolt', 26, 3.4, ['Bolts']),
        new SkillItem('25 x Arrow Shaft (Willow)', 30, 10, ['Arrows']),
        new SkillItem('Steel Arrow', 30, 6.3, ['Arrows']),
        new SkillItem('Kebbit Bolt', 32, 5.8, ['Bolts']),
        new SkillItem('Willow Shortbow (Cut)', 35, 33.3, ['Bows']),
        new SkillItem('Willow Shortbow (String)', 35, 33.2, ['Bows']),
        new SkillItem('Willow Shortbow', 35, 66.5, ['Bows']),
        new SkillItem('Steel Dart', 37, 7.5, ['Darts']),
        new SkillItem('Iron Bolt', 39, 1.5, ['Bolts']),
        new SkillItem('Iron Crossbow Stock (Willow)', 39, 22, ['Crossbows']),
        new SkillItem('Iron Crossbow', 39, 88, ['Crossbows']),
        new SkillItem('Pearl Tipped Bolt', 41, 4.7, ['Bolts']),
        new SkillItem('Long Kebbit Bolt', 42, 7.9, ['Bolts']),
        new SkillItem('Silver Bolt', 43, 2.5, ['Bolts']),
        new SkillItem('30 x Arrow Shaft (Maple)', 45, 12.5, ['Arrows']),
        new SkillItem('Mithril Arrow', 45, 8.8, ['Arrows']),
        new SkillItem('Steel Bolt', 46, 3.5, ['Bolts']),
        new SkillItem('Steel Crossbow Stock (Teak)', 46, 27, ['Crossbows']),
        new SkillItem('Steel Crossbow', 46, 108, ['Crossbows']),
        new SkillItem('Red Topaz Bolt', 48, 7.4, ['Bolts']),
        new SkillItem('Maple Shortbow (Cut/String)', 50, 50, ['Bows']),
        new SkillItem('Maple Shortbow', 50, 100, ['Bows']),
        new SkillItem('Mithril Dart', 52, 11.2, ['Darts']),
        new SkillItem('Broad Arrow', 52, 15, ['Arrows']),
        new SkillItem('Mithril Bolt', 54, 5, ['Bolts']),
        new SkillItem('Mithril Crossbow Stock (Maple)', 54, 32, ['Crossbows']),
        new SkillItem('Mithril Crossbow', 54, 128, ['Crossbows']),
        new SkillItem('Broad Tipped Bolt', 55, 3, ['Bolts']),
        new SkillItem('Sapphire Tipped Bolt', 56, 9.7, ['Bolts']),
        new SkillItem('Emerald Tipped Bolt', 58, 10.5, ['Bolts']),
        new SkillItem('Mithril Grapple', 59, 16, ['Bolts']),
        new SkillItem('35 x Arrow Shaft (Yew)', 60, 15, ['Arrows']),
        new SkillItem('Adamant Arrow', 60, 11.3, ['Arrows']),
        new SkillItem('Adamant Bolt', 61, 7, ['Bolts']),
        new SkillItem('Adamant Crossbow Stock (Mahogany)', 61, 41, ['Crossbows']),
        new SkillItem('Adamant Crossbow', 61, 164, ['Crossbows']),
        new SkillItem('Ruby Tipped Bolt', 63, 13.3, ['Bolts']),
        new SkillItem('Diamond Tipped Bolt', 65, 14, ['Bolts']),
        new SkillItem('Yew Shortbow (Cut/String)', 65, 67.5, ['Bows']),
        new SkillItem('Yew Shortbow', 65, 135, ['Bows']),
        new SkillItem('Adamant Dart', 67, 15, ['Darts']),
        new SkillItem('Rune Bolt', 69, 10, ['Bolts']),
        new SkillItem('Rune Crossbow Stock (Yew)', 69, 50, ['Crossbows']),
        new SkillItem('Rune Crossbow', 69, 200, ['Crossbows']),
        new SkillItem('Blisterwood Items', 70, 100, ['Other', 'Darts']),
        new SkillItem('Dragonstone Tipped Bolt', 71, 18.2, ['Bolts']),
        new SkillItem('Onyx Tipped Bolt', 73, 19.4, ['Bolts']),
        new SkillItem('40 x Arrow Shaft (Magic)', 75, 17.5, ['Arrows']),
        new SkillItem('Rune Arrow', 75, 13.8, ['Arrows']),
        new SkillItem('Bane Arrow', 76, 10, ['Arrows']),
        new SkillItem('Magic Shortbow (Cut)', 80, 83.3, ['Bows']),
        new SkillItem('Magic Shortbow (String)', 80, 83.2, ['Bows']),
        new SkillItem('Magic Shortbow', 80, 166.5, ['Bows']),
        new SkillItem('Rune Dart', 81, 18.1, ['Darts']),
        new SkillItem('Bolas', 87, 50, ['Other']),
        new SkillItem('Dragon Arrow', 90, 16.3, ['Arrows']),
        new SkillItem('Dragon Dart', 95, 25, ['Darts']),
    ]
};