skill_info[15] = {
    name: 'Herblore',
    categories: {
        title: 'Type',
        values: ['Normal', 'Juju']
    },
    subcategories: {
        title: 'Category',
        values: ['Potions', 'Herbs', 'Tar']
    },
    items: [
        // Regular Potions/Herbs/Tar
        new SkillItem('Clean Guam', 1, 2.5, ['Normal', 'Herbs']),
        new SkillItem('Attack Potion', 1, 25, ['Normal', 'Potions']),
        new SkillItem('Ranging Potion', 3, 30, ['Normal', 'Potions']),
        new SkillItem('Clean Tarromin', 5, 3.8, ['Normal', 'Herbs']),
        new SkillItem('Magic Potion', 5, 35, ['Normal', 'Potions']),
        new SkillItem('Strength Potion', 7, 40, ['Normal', 'Potions']),
        new SkillItem('Relicyms Balm', 8, 40, ['Normal', 'Potions']),
        new SkillItem('Clean Marrentill', 9, 5, ['Normal', 'Herbs']),
        new SkillItem('Defence Potion', 9, 45, ['Normal', 'Potions']),
        new SkillItem('Antipoison', 13, 50, ['Normal', 'Potions']),
        new SkillItem('Serum 207', 15, 50,['Normal', 'Potions']),
        new SkillItem('Guthix Rest', 18, 59, ['Normal', 'Potions']),
        new SkillItem('Guam Tar', 19, 30, ['Normal', 'Tar']),
        new SkillItem('Clean Harralander', 20, 6.3, ['Normal', 'Herbs']),
        new SkillItem('Stat Restore Potion', 22, 62.5, ['Normal', 'Potions']),
        new SkillItem('Guthix Balance', 22, 50, ['Normal', 'Potions']),
        new SkillItem('Guthix Balance + Stat Restore', 22, 112.5, ['Normal', 'Potions']),
        new SkillItem('Clean Ranarr Weed', 25, 7.5, ['Normal', 'Herbs']),
        new SkillItem('Blamish Oil', 25, 80, ['Normal', 'Potions']),
        new SkillItem('Energy Potion', 26, 67.5, ['Normal', 'Potions']),
        new SkillItem('Clean Toadflax', 30, 8, ['Normal', 'Herbs']),
        new SkillItem('Marrentill Tar', 31, 42.5, ['Normal', 'Tar']),
        new SkillItem('Super Fishing Explosive', 31, 55, ['Normal', 'Potions']),
        new SkillItem('Agility Potion', 34, 80, ['Normal', 'Potions']),
        new SkillItem('Clean Spirit Weed', 35, 7.8, ['Normal', 'Herbs']),
        new SkillItem('Combat Potion', 36, 84, ['Normal', 'Potions']),
        new SkillItem('Prayer Potion', 38, 87.5, ['Normal', 'Potions']),
        new SkillItem('Tarromin Tar', 39, 55, ['Normal', 'Tar']),
        new SkillItem('Clean Irit', 40, 8.8, ['Normal', 'Herbs']),
        new SkillItem('Summoning Potion', 40, 92, ['Normal', 'Potions']),
        new SkillItem('Clean Wergali', 41, 9.5, ['Normal', 'Herbs']),
        new SkillItem('Crafting Potion', 42, 95, ['Normal', 'Potions']),
        new SkillItem('Harralander Tar', 44, 72.5, ['Normal', 'Tar']),
        new SkillItem('Super Attack Potion', 45, 100, ['Normal', 'Potions']),
        new SkillItem('Super Antipoison', 48, 106.3, ['Normal', 'Potions']),
        new SkillItem('Clean Avantoe', 48, 10, ['Normal', 'Herbs']),
        new SkillItem('Fishing Potions', 50, 112.5, ['Normal', 'Potions']),
        new SkillItem('Super Energy Potion', 52, 117.5, ['Normal', 'Potions']),
        new SkillItem('Hunter Potion', 53, 120, ['Normal', 'Potions']),
        new SkillItem('Clean Kwuarm', 54, 11.3, ['Normal', 'Herbs']),
        new SkillItem('Super Strength Potion', 55, 125, ['Normal', 'Potions']),
        new SkillItem('Magic Essence', 57, 130, ['Normal', 'Potions']),
        new SkillItem('Fletching Potion', 58, 132, ['Normal', 'Potions']),
        new SkillItem('Clean Snapdragon', 59, 11.8, ['Normal', 'Herbs']),
        new SkillItem('Weapon Poison', 60, 137.5, ['Normal', 'Potions']),
        new SkillItem('Super Stat Restore Potion', 63, 142.5, ['Normal', 'Potions']),
        new SkillItem('Sanfew Serum (3)', 65, 160, ['Normal', 'Potions']),
        new SkillItem('Sanfew Serum (3) + Super Restore', 65, 302.5, ['Normal', 'Potions']),
        new SkillItem('Super Defence Potion', 66, 150, ['Normal', 'Potions']),
        new SkillItem('Clean Lantadyme', 67, 13.1, ['Normal', 'Herbs']),
        new SkillItem('Antipoison+', 68, 155, ['Normal', 'Potions']),
        new SkillItem('Antifire', 69, 157.5, ['Normal', 'Potions']),
        new SkillItem('Clean Dwarf Weed', 70, 13.8, ['Normal', 'Herbs']),
        new SkillItem('Super Ranging Potion', 72, 162.5, ['Normal', 'Potions']),
        new SkillItem('Weapon Poison+', 73, 165, ['Normal', 'Potions']),
        new SkillItem('Clean Torstol', 75, 15, ['Normal', 'Herbs']),
        new SkillItem('Super Magic Potion', 76, 172.5, ['Normal', 'Potions']),
        new SkillItem('Zamorak Brew', 78, 175, ['Normal', 'Potions']),
        new SkillItem('Antipoison++', 79, 177.5, ['Normal',' Potions']),
        new SkillItem('Saradomin Brew', 81, 180, ['Normal', 'Potions']),
        new SkillItem('Weapon Poison++', 82, 190, ['Normal', 'Potions']),
        new SkillItem('Super Antifire', 85, 210, ['Normal', 'Potions']),
        new SkillItem('Super Antifire + Antifire', 85, 367.5, ['Normal', 'Potions']),
        new SkillItem('Extreme Attack', 88, 220, ['Normal', 'Potions']),
        new SkillItem('Extreme Attack + Super Attack', 89, 320, ['Normal', 'Potions']),
        new SkillItem('Extreme Strength', 89, 230, ['Normal', 'Potions']),
        new SkillItem('Extreme Strength + Super Strength', 89, 355, ['Normal', 'Potions']),
        new SkillItem('Extreme Defence', 90, 240, ['Normal', 'Potions']),
        new SkillItem('Extreme Defence + Super Defence', 90, 390, ['Normal', 'Potions']),
        new SkillItem('Clean Fellstalk', 91, 16.8, ['Normal', 'Herbs']),
        new SkillItem('Extreme Magic', 91, 250, ['Normal', 'Potions']),
        new SkillItem('Extreme Magic + Super Magic', 91, 422.5, ['Normal', 'Potions']),
        new SkillItem('Extreme Ranging', 92, 260, ['Normal', 'Potions']),
        new SkillItem('Extreme Ranging + Super Ranging', 92, 422.5, ['Normal', 'Potions']),
        new SkillItem('Prayer Renewal', 94, 270, ['Normal', 'Potions']),
        new SkillItem('Super Prayer', 94, 270, ['Normal', 'Potions']),
        new SkillItem('Super Prayer + Prayer', 94, 357.5, ['Normal', 'Potions']),
        new SkillItem('Overload', 96, 1000, ['Normal', 'Potions']),
        new SkillItem('Overload + Extremes', 96, 2200, ['Normal', 'Potions']),
        new SkillItem('Overload + Extremes + Supers', 96, 2910, ['Normal', 'Potions']),
        // Juju Potions
        new SkillItem('Juju Hunter Potion', 54, 123, ['Juju', 'Potions']),
        new SkillItem('Juju Scentless Potion', 59, 135, ['Juju', 'Potions']),
        new SkillItem('Juju Farming Potion', 64, 146, ['Juju', 'Potions']),
        new SkillItem('Juju Cooking Potion', 67, 152, ['Juju', 'Potions']),
        new SkillItem('Juju Fishing Potion', 70, 158, ['Juju', 'Potions']),
        new SkillItem('Juju Woodcutting Potion', 71, 160, ['Juju', 'Potions']),
        new SkillItem('Juju Mining Potion', 71, 160, ['Juju', 'Potions']),
        new SkillItem('Saradomin\'s Blessing', 75, 170, ['Juju', 'Potions']),
        new SkillItem('Zamorak\'s Favour', 75, 170, ['Juju', 'Potions']),
        new SkillItem('Guthix\'s Gift', 75, 170, ['Juju', 'Potions']),
        // Juju Herbs
        new SkillItem('Clean Erzille', 54, 10, ['Juju', 'Herbs']),
        new SkillItem('Clean Ugune', 56, 11.5, ['Juju', 'Herbs']),
        new SkillItem('Clean Argway', 57, 11.6, ['Juju', 'Herbs']),
        new SkillItem('Clean Shengo', 58, 11.7, ['Juju', 'Herbs']),
        new SkillItem('Clean Samaden', 59, 11.7, ['Juju', 'Herbs']),
    ]
};
