skill_info[21] = {
    name: 'Hunter',
    categories: {
        title: 'Category',
        values: ['Box Trap', 'Butterfly Net', 'Deadfall Trap', 'Herblore Habitat', 'Net Trap', 'Pitfall Trap', 'Snare Trap', 'Tracking', 'Implings']
    },
    items: [
        // Box Trap
        new SkillItem('Ferret', 27, 115.2, ['Box Trap']),
        new SkillItem('Platypus', 48, 205, ['Box Trap']),
        new SkillItem('Chinchompa', 53, 198.4, ['Box Trap']),
        new SkillItem('Penguin (Box)', 56, 150, ['Box Trap']),
        new SkillItem('Red Chinchompa', 63, 265, ['Box Trap']),
        new SkillItem('Pawya', 66, 400, ['Box Trap']),
        new SkillItem('Polar Kebbit (Box)', 70, 253, ['Box Trap']),
        new SkillItem('Imp', 71, 450, ['Box Trap']),
        new SkillItem('Grenwall', 77, 1100, ['Box Trap']),
        // Butterfly Net
        new SkillItem('Ruby Harvest', 15, 24, ['Butterfly Net']),
        new SkillItem('Sapphire Glacialis', 25, 34, ['Butterfly Net']),
        new SkillItem('Snowy Knight', 35, 44, ['Butterfly Net']),
        new SkillItem('Black Warlock', 45, 54, ['Butterfly Net']),
        new SkillItem('Ruby Harvest (Barehanded)', 80, 300, ['Butterfly Net']),
        new SkillItem('Sapphire Glacialis (Barehanded)', 85, 400, ['Butterfly Net']),
        new SkillItem('Snowy Knight (Barehanded)', 90, 500, ['Butterfly Net']),
        new SkillItem('Black Warlock (Barehanded)', 95, 650, ['Butterfly Net']),
        // Deadfall Trap
        new SkillItem('Wild Kebbit', 23, 128, ['Deadfall Trap']),
        new SkillItem('Barb-tailed Kebbit', 33, 168, ['Deadfall Trap']),
        new SkillItem('Prickly Kebbit', 37, 204, ['Deadfall Trap']),
        new SkillItem('Diseased Kebbit', 44, 225, ['Deadfall Trap']),
        new SkillItem('Penguin (Deadfall)', 51, 210, ['Deadfall Trap']),
        new SkillItem('Sabre-toothed Kebbit', 51, 200, ['Deadfall Trap']),
        // Herblore Habitat
        new SkillItem('Common Jadinko', 70, 350, ['Herblore Habitat']),
        new SkillItem('Shadow Jadinko', 71, 475, ['Herblore Habitat']),
        new SkillItem('Igneous Jadinko', 74, 465, ['Herblore Habitat']),
        new SkillItem('Cannibal Jadinko', 75, 475, ['Herblore Habitat']),
        new SkillItem('Aquatic Jadinko', 76, 475, ['Herblore Habitat']),
        new SkillItem('Amphibian Jadinko', 77, 485, ['Herblore Habitat']),
        new SkillItem('Carrion Jadinko', 78, 505, ['Herblore Habitat']),
        new SkillItem('Diseased Jadinko', 78, 580.5, ['Herblore Habitat']),
        new SkillItem('Camouflaged Jadinko', 79, 600, ['Herblore Habitat']),
        new SkillItem('Draconic Jadinko', 80, 525, ['Herblore Habitat']),
        new SkillItem('Saradomin Jadinko', 81, 600, ['Herblore Habitat']),
        new SkillItem('Zamorak Jadinko', 81, 600, ['Herblore Habitat']),
        // Net Trap
        new SkillItem('Swamp Lizard', 29, 152, ['Net Trap']),
        new SkillItem('Orange Salamander', 47, 224, ['Net Trap']),
        new SkillItem('Penguin (Net)', 50, 250, ['Net Trap']),
        new SkillItem('Red Salamander', 59, 272, ['Net Trap']),
        new SkillItem('Black Salamander', 67, 304, ['Net Trap']),
        // Pitfall Trap
        new SkillItem('Spined Larupia', 31, 180, ['Pitfall Trap']),
        new SkillItem('Horned Graahk', 41, 240, ['Pitfall Trap']),
        new SkillItem('Sabre-toothed Kyatt', 55, 300, ['Pitfall Trap']),
        // Snare Trap
        new SkillItem('Crimson Swift', 1, 34, ['Snare Trap']),
        new SkillItem('Golden Warbler', 5, 47.6, ['Snare Trap']),
        new SkillItem('Copper Longtail', 9, 61.2, ['Snare Trap']),
        new SkillItem('Cerulean Twitch', 11, 64.6, ['Snare Trap']),
        new SkillItem('Tropical Wagtail', 19, 95.2, ['Snare Trap']),
        new SkillItem('Rabbit', 27, 144, ['Snare Trap']),
        new SkillItem('Wimpy Bird', 39, 167, ['Snare Trap']),
        // Tracking
        new SkillItem('Polar Kebbit (Tracking)', 1, 30, ['Tracking']),
        new SkillItem('Common Kebbit', 3, 36, ['Tracking']),
        new SkillItem('Feldip Weasel', 7, 48, ['Tracking']),
        new SkillItem('Disert Devil', 13, 66, ['Tracking']),
        new SkillItem('Razor-backed Kebbit', 49, 348, ['Tracking']),
        // Implings
        new SkillItem('Baby Impling (Puro-Puro)', 17, 20, ['Implings']),
        new SkillItem('Baby Impling (World)', 17, 25, ['Implings']),
        new SkillItem('Young Impling (Puro-Puro)', 22, 48, ['Implings']),
        new SkillItem('Young Impling (World)', 22, 65, ['Implings']),
        new SkillItem('Gourmet Impling (Puro-Puro)', 28, 82, ['Implings']),
        new SkillItem('Gourmet Impling (World)', 28, 113, ['Implings']),
        new SkillItem('Earth Impling (Puro-Puro)', 36, 126, ['Implings']),
        new SkillItem('Earth Impling (World)', 36, 177, ['Implings']),
        new SkillItem('Essence Impling (Puro-Puro)', 42, 160, ['Implings']),
        new SkillItem('Essence Impling (World)', 42, 225, ['Implings']),
        new SkillItem('Ecletic Impling (Puro-Puro)', 50, 205, ['Implings']),
        new SkillItem('Ecletic Impling (World)', 50, 289, ['Implings']),
        new SkillItem('Spirit Impling (Puro-Puro)', 54, 227, ['Implings']),
        new SkillItem('Spirit Impling (World)', 54, 321, ['Implings']),
        new SkillItem('Nature Impling (Puro-Puro)', 58, 250, ['Implings']),
        new SkillItem('Nature Impling (World)', 58, 353, ['Implings']),
        new SkillItem('Magpie Impling (Puro-Puro)', 65,289, ['Implings']),
        new SkillItem('Magpie Impling (World)', 65, 409, ['Implings']),
        new SkillItem('Ninja Impling (Puro-Puro)', 74, 339, ['Implings']),
        new SkillItem('Ninja Impling (World)', 74, 481, ['Implings']),
        new SkillItem('Pirate Impling (Puro-Puro)', 76, 350, ['Implings']),
        new SkillItem('Pirate Impling (World)', 76, 497, ['Implings']),
        new SkillItem('Dragon Impling (Puro-Puro)', 83, 390, ['Implings']),
        new SkillItem('Dragon Impling (World)', 83, 553, ['Implings']),
        new SkillItem('Zombie Impling (Puro-Puro)', 87, 412, ['Implings']),
        new SkillItem('Zombie Impling (World)', 87, 585, ['Implings']),
        new SkillItem('Kingly Impling (Puro-Puro)', 91, 434, ['Implings']),
        new SkillItem('Kingly Impling (World)', 91, 617, ['Implings']),
    ]
};
