skill_info[6] = {
    name: 'Magic',
    categories: {
        title: 'Spellbook',
        values: ['Regular', 'Ancient', 'Lunar']
    },
    subcategories: {
        title: 'Spell Type',
        values: ['Damage', 'Combat', 'Enchant', 'Teleport', 'Skill', 'Other']
    },
    items: [
        // Regular spellbook
        new SkillItem('Wind Rush', 1, 3.7, ['Regular', 'Damage']),
        new SkillItem('Wind Strike', 1, 7.5, ['Regular', 'Damage']),
        new SkillItem('Confuse', 3, 13, ['Regular', 'Combat']),
        new SkillItem('Enchant Crossbow Bolt (Opal)', 4, 9, ['Regular', 'Enchant']),
        new SkillItem('Water Strike', 5, 11.5, ['Regular', 'Damage']),
        new SkillItem('Enchant Crossbow Bolt (Sapphire)', 7, 17 ['Regular', 'Enchant']),
        new SkillItem('Enchant Lvl-1 Jewellery', 7, 17, ['Regular', 'Enchant']),
        new SkillItem('Earth Strike', 9, 15.5, ['Regular', 'Damage']),
        new SkillItem('Mobilising Armies Teleport', 10, 19, ['Regular', 'Teleport']),
        new SkillItem('Weaken', 11, 21, ['Regular', 'Combat']),
        new SkillItem('Fire Strike', 13, 19.5, ['Regular', 'Damage']),
        new SkillItem('Enchant Crossbow Bolt (Jade)', 14, 19, ['Regular', 'Enchant']),
        new SkillItem('Bones to Bananas', 15, 25, ['Regular', 'Other']),
        new SkillItem('Wind Bolt', 17, 22.5, ['Regular', 'Damage']),
        new SkillItem('Curse', 19, 29, ['Regular', 'Combat']),
        new SkillItem('Bind', 20, 30, ['Regular', 'Combat']),
        new SkillItem('Low Level Alchemy', 21, 31, ['Regular', 'Other']),
        new SkillItem('Water Bolt', 23, 26.5, ['Regular', 'Damage']),
        new SkillItem('Enchant Crossbow Bolt (Pearl)', 24, 29, ['Regular', 'Enchant']),
        new SkillItem('Varrock Teleport', 25, 35, ['Regular', 'Teleport']),
        new SkillItem('Enchant Crossbow Bolt (Emerald)', 27, 37, ['Regular', 'Enchant']),
        new SkillItem('Enchant Lvl-2 Jewellery', 27, 37, ['Regular', 'Enchant']),
        new SkillItem('Earth Bolt', 29, 30.5, ['Regular', 'Damage']),
        new SkillItem('Enchant Crossbow Bolt (Red Topaz)', 29, 34, ['Regular', 'Enchant']),
        new SkillItem('Lumbridge Teleport', 31, 41, ['Regular', 'Teleport']),
        new SkillItem('Telegrab', 33, 43, ['Regular', 'Other']),
        new SkillItem('Fire Bolt', 35, 34.5, ['Regular', 'Damage']),
        new SkillItem('Falador Teleport', 37, 48, ['Regular', 'Teleport']),
        new SkillItem('Crumble Undead', 39, 39.5, ['Regular', 'Damage']),
        new SkillItem('House Teleport', 40, 30, ['Regular', 'Teleport']),
        new SkillItem('Wind Blast', 41, 38.5, ['Regular', 'Damage']),
        new SkillItem('Superheat Item', 43, 53, ['Regular', 'Other']),
        new SkillItem('Camelot Teleport', 45, 55.5, ['Regular', 'Teleport']),
        new SkillItem('Water Blast', 47, 42.5, ['Regular', 'Damage']),
        new SkillItem('Enchant Crossbow Bolt (Ruby)', 49, 59, ['Regular', 'Enchant']),
        new SkillItem('Enchant Lvl-3 Jewellery', 49, 59, ['Regular', 'Enchant']),
        new SkillItem('Iban Blast', 50, 67.5, ['Regular', 'Damage']),
        new SkillItem('Snare', 50, 62, ['Regular', 'Combat']),
        new SkillItem('Ardougne Teleport', 51, 61, ['Regular', 'Teleport']),
        new SkillItem('Earth Blast', 53, 46.5, ['Regular', 'Damage']),
        new SkillItem('High Level Alchemy', 55, 65, ['Regular', 'Other']),
        new SkillItem('Charge Water Orb', 56, 66, ['Regular', 'Other']),
        new SkillItem('Enchant Crossbow Bolt (Diamond)', 57, 67, ['Regular', 'Enchant']),
        new SkillItem('Enchant Lvl-4 Jewellery', 57, 67, ['Regular', 'Enchant']),
        new SkillItem('Watchtower Teleport', 58, 68, ['Regular', 'Teleport']),
        new SkillItem('Fire Blast', 59, 50.5, ['Regular', 'Damage']),
        new SkillItem('Bones to Peaches', 60, 33.5, ['Regular', 'Other']),
        new SkillItem('God Spell', 60, 55, ['Regular', 'Damage']),
        new SkillItem('God Spell (Charged)', 60, 65, ['Regular', 'Damage']),
        new SkillItem('Charge Earth Orb', 60, 70, ['Regular', 'Other']),
        new SkillItem('Trollheim Teleport', 61, 68, ['Regular', 'Teleport']),
        new SkillItem('Wind Wave', 62, 53, ['Regular', 'Damage']),
        new SkillItem('Charge Fire Orb', 63, 73, ['Regular', 'Other']),
        new SkillItem('Ape Atoll Teleport', 64, 74, ['Regular', 'Teleport']),
        new SkillItem('Water Wave', 65, 55.5, ['Regular', 'Damage']),
        new SkillItem('Charge Air Orb', 66, 76, ['Regular', 'Other']),
        new SkillItem('Vulnerability', 66, 76, ['Regular', 'Combat']),
        new SkillItem('Enchant Crossbow Bolt (Dragonstone)', 68, 78, ['Regular', 'Enchant']),
        new SkillItem('Enchant Lvl-5 Jewellery', 68, 78, ['Regular', 'Enchant']),
        new SkillItem('Earth Wave', 70, 59, ['Regular', 'Damage']),
        new SkillItem('Enfeeble', 73, 83, ['Regular', 'Damage']),
        new SkillItem('Teleother Lumbridge', 74, 84, ['Regular', 'Teleport']),
        new SkillItem('Fire Wave', 75, 62.5, ['Regular', 'Damage']),
        new SkillItem('Entangle', 79, 94, ['Regular', 'Combat']),
        new SkillItem('Stun', 80, 90, ['Regular', 'Combat']),
        new SkillItem('Charge', 80, 180, ['Regular', 'Combat']),
        new SkillItem('Wind Surge', 81, 97, ['Regular', 'Damage']),
        new SkillItem('Teleother Falador', 82, 92, ['Regular', 'Teleport']),
        new SkillItem('Teleport Block', 85, 80, ['Regular', 'Combat']),
        new SkillItem('Water Surge', 85, 104, ['Regular', 'Damage']),
        new SkillItem('Enchant Crossbow Bolt (Onyx)', 87, 97, ['Regular', 'Enchant']),
        new SkillItem('Enchant Lvl-6 Jewellery', 87, 97, ['Regular', 'Enchant']),
        new SkillItem('Teleother Camelot', 90, 100, ['Regular', 'Teleport']),
        new SkillItem('Earth Surge', 90, 111, ['Regular', 'Damage']),
        new SkillItem('Fire Surge', 95, 118, ['Regular', 'Damage']),
        // Ancient Spellbook
        new SkillItem('Smoke Rush', 50, 43, ['Ancient', 'Damage']),
        new SkillItem('Shadow Rush', 52, 45, ['Ancient', 'Damage']),
        new SkillItem('Paddewa Teleport', 54, 64, ['Ancient', 'Teleport']),
        new SkillItem('Blood Rush', 56, 48, ['Ancient', 'Damage']),
        new SkillItem('Ice Rush', 58, 50, ['Ancient', 'Damage']),
        new SkillItem('Senntisten Teleport', 60, 70, ['Ancient', 'Teleport']),
        new SkillItem('Miasmic Rush', 62, 54, ['Ancient', 'Damage']),
        new SkillItem('Smoke Burst', 62, 53, ['Ancient', 'Damage']),
        new SkillItem('Shadow Burst', 64, 55, ['Ancient', 'Damage']),
        new SkillItem('Kharyll Teleport', 66, 76, ['Ancient', 'Teleport']),
        new SkillItem('Blood Burst', 68, 60, ['Ancient', 'Damage']),
        new SkillItem('Ice Burst', 70, 62, ['Ancient', 'Damage']),
        new SkillItem('Lassar Teleport', 72, 82, ['Ancient', 'Teleport']),
        new SkillItem('Miasmic Burst', 73, 66, ['Ancient', 'Damage']),
        new SkillItem('Smoke Blitz', 74, 65, ['Ancient', 'Damage']),
        new SkillItem('Shadow Blitz', 76, 67, ['Ancient', 'Damage']),
        new SkillItem('Dareeyak Teleport', 78, 88, ['Ancient', 'Teleport']),
        new SkillItem('Blood Blitz', 80, 70, ['Ancient', 'Damage']),
        new SkillItem('Ice Blitz', 82, 72, ['Ancient', 'Damage']),
        new SkillItem('Carrallangar Teleport', 84, 94, ['Ancient', 'Teleport']),
        new SkillItem('Miasmic Blitz', 85, 76, ['Ancient', 'Damage']),
        new SkillItem('Smoke Barrage', 86, 75, ['Ancient', 'Damage']),
        new SkillItem('Shadow Barrage', 88, 77, ['Ancient', 'Damage']),
        new SkillItem('Annakarl Teleport', 90, 100, ['Ancient', 'Teleport']),
        new SkillItem('Blood Barrage', 92, 80, ['Ancient', 'Damage']),
        new SkillItem('Ice Barrage', 94, 82, ['Ancient', 'Damage']),
        new SkillItem('Ghorrock Teleport', 96, 106, ['Ancient', 'Teleport']),
        new SkillItem('Miasmic Barrage', 97, 86, ['Ancient', 'Damage']),
        // Lunar Spellbook
        new SkillItem('Bake Pie', 65, 60, ['Lunar', 'Skill']),
        new SkillItem('Cure Plant', 66, 60, ['Lunar', 'Skill']),
        new SkillItem('Monster Examine', 66, 61, ['Lunar', 'Other']),
        new SkillItem('NPC Contact', 67, 63, ['Lunar', 'Other']),
        new SkillItem('Cure Other', 68, 65, ['Lunar', 'Combat']),
        new SkillItem('Humidify', 68, 65, ['Lunar', 'Skill']),
        new SkillItem('Moonclan Teleport', 69, 66, ['Lunar', 'Teleport']),
        new SkillItem('Moonclan Group Teleport', 70, 67, ['Lunar', 'Teleport']),
        new SkillItem('Ourania Teleport', 71, 69, ['Lunar', 'Teleport']),
        new SkillItem('Cure Me', 71, 69, ['Lunar', 'Combat']),
        new SkillItem('Hunter Kit', 71, 70, ['Lunar', 'Skill']),
        new SkillItem('South Falador Teleport', 72, 70, ['Lunar', 'Teleport']),
        new SkillItem('Waterbirth Teleport', 72, 71, ['Lunar', 'Teleport']),
        new SkillItem('South Falador Group Teleport', 73, 72, ['Lunar', 'Teleport']),
        new SkillItem('Cure Group', 74, 74, ['Lunar', 'Combat']),
        new SkillItem('Repair Rune Pouch', 75, 75, ['Lunar', 'Skill']),
        new SkillItem('Barbarian Teleport', 75, 76, ['Lunar', 'Teleport']),
        new SkillItem('Stat Spy', 75, 76, ['Lunar', 'Other']),
        new SkillItem('Barbarian Group Teleport', 76, 77, ['Lunar', 'Teleport']),
        new SkillItem('North Ardougne Teleport', 76, 76, ['Lunar', 'Teleport']),
        new SkillItem('Superglass Make', 77, 78, ['Lunar', 'Skill']),
        new SkillItem('Remote Farming', 78, 79, ['Lunar', 'Skill']),
        new SkillItem('Khazard Teleport', 78, 80, ['Lunar', 'Teleport']),
        new SkillItem('Khazard Group Teleport', 79, 81, ['Lunar', 'Teleport']),
        new SkillItem('Dream', 79, 82, ['Lunar', 'Other']),
        new SkillItem('Spiritualize Food', 80, 81, ['Lunar', 'Other']),
        new SkillItem('String Jewellery', 80, 83, ['Lunar', 'Skill']),
        new SkillItem('Stat Restore Pot Share', 81, 84, ['Lunar', 'Combat']),
        new SkillItem('Magic Imbue', 82, 86, ['Lunar', 'Skill']),
        new SkillItem('Make Leather', 83, 87, ['Lunar', 'Skill']),
        new SkillItem('Fertile Soil', 83, 87, ['Lunar', 'Skill']),
        new SkillItem('Boost Potion Share', 84, 88, ['Lunar', 'Combat']),
        new SkillItem('Fishing Guild Teleport', 85, 89, ['Lunar', 'Teleport']),
        new SkillItem('Fishing Guild Group Teleport', 86, 90, ['Lunar', 'Teleport']),
        new SkillItem('Plank Make', 86, 90, ['Lunar', 'Skill']),
        new SkillItem('Catherby Teleport', 87, 92, ['Lunar', 'Teleport']),
        new SkillItem('Tune Bane Ore', 87, 90, ['Lunar', 'Other']),
        new SkillItem('Catherby Group Teleport', 88, 93, ['Lunar', 'Teleport']),
        new SkillItem('Ice Plateau Teleport', 89, 96, ['Lunar', 'Teleport']),
        new SkillItem('Disruption Shield', 90, 97, ['Lunar', 'Combat']),
        new SkillItem('Energy Transfer', 91, 100, ['Lunar', 'Combat']),
        new SkillItem('Heal Other', 92, 101, ['Lunar', 'Combat']),
        new SkillItem('Vengeance Other', 93, 108, ['Lunar', 'Combat']),
        new SkillItem('Vengeance', 94, 112, ['Lunar', 'Combat']),
        new SkillItem('Vengeance Group', 95, 120, ['Lunar', 'Combat']),
        new SkillItem('Heal Group', 95, 124, ['Lunar', 'Combat']),
        new SkillItem('Spellbook Swap', 96, 130, ['Lunar', 'Other']),
    ]
};