skill_info[14] = {
    name: 'Mining',
    items: [
        new SkillItem('Rune Essence', 1, 5),
        new SkillItem('Clay', 1, 5),
        new SkillItem('Copper', 1, 17.5),
        new SkillItem('Tin', 1, 17.5),
        new SkillItem('Limestone', 10, 26.5),
        new SkillItem('Iron', 15, 35),
        new SkillItem('Silver', 20, 40),
        new SkillItem('Coal', 30, 50),
        new SkillItem('Pure Essence', 30, 5),
        new SkillItem('Sandstone (1kg)', 35, 30),
        new SkillItem('Sandstone (2kg)', 35, 40),
        new SkillItem('Sandstone (5kg)', 35, 50),
        new SkillItem('Sandstone (10kg)', 35, 60),
        new SkillItem('Gem Rock', 40, 65),
        new SkillItem('Gold', 40, 65),
        new SkillItem('Granite (500g)', 45, 50),
        new SkillItem('Granite (2kg)', 45, 60),
        new SkillItem('Granite (5kg)', 45, 75),
        new SkillItem('Mithril', 55, 80),
        new SkillItem('Lava Flow Crust', 68, 100),
        new SkillItem('Adamantite', 70, 95),
        new SkillItem('Living Rock Remains', 73, 25),
        new SkillItem('Bane', 77, 90),
        new SkillItem('Concentrated Coal Deposit', 77, 50),
        new SkillItem('Concentrated Gold Deposit', 80, 65),
        new SkillItem('Runite', 85, 125)
    ]
};