skill_info[13] = {
    name: 'Smithing',
    categories: {
        title: 'Category',
        values: ['Smelting', 'Smithing', 'Smelting + Smithing', 'Artisans Workshop', 'Spears/Hastae']
    },
    items: [
        // Regular Bars: Smelting/Smithing/Total
        new SkillItem('Bronze Bar', 1, 6.2, ['Smelting']),
        new SkillItem('Bronze (Smithing)', 1, 12.5, ['Smithing']),
        new SkillItem('Bronze (Total)', 1, 18.7, ['Smelting + Smithing']),
        new SkillItem('Blurite Bar', 8, 8, ['Smelting']),
        new SkillItem('Blurite (Smithing)', 8, 17, ['Smithing']),
        new SkillItem('Blurite (Total)', 8, 25, ['Smelting + Smithing']),
        new SkillItem('Iron Bar', 15, 12.5, ['Smelting']),
        new SkillItem('Iron (Smithing)', 15, 25, ['Smithing']),
        new SkillItem('Iron (Total)', 15, 37.5, ['Smelting + Smithing']),
        new SkillItem('Silver Bar', 20, 13.7, ['Smelting']),
        new SkillItem('Steel Bar', 30, 17.5, ['Smelting']),
        new SkillItem('Steel (Smithing)', 30, 37.5, ['Smithing']),
        new SkillItem('Steel (Total)', 30, 55, ['Smelting + Smithing']),
        new SkillItem('4 Cannonballs', 35, 25.6, ['Smelting']),
        new SkillItem('4 Cannonballs + Steel Bar', 35, 43.1, ['Smelting']),
        new SkillItem('Gold Bar', 40, 22.5, ['Smelting']),
        new SkillItem('Gold (Gauntlets)', 40, 56.2, ['Smelting']),
        new SkillItem('Mithril Bar', 50, 30, ['Smelting']),
        new SkillItem('Mithril (Smithing)', 50, 50, ['Smithing']),
        new SkillItem('Mithril (Total)', 50, 80, ['Smelting + Smithing']),
        new SkillItem('Adamant Bar', 70, 37.5, ['Smelting']),
        new SkillItem('Adamant (Smithing)', 70, 62.5, ['Smithing']),
        new SkillItem('Adamant (Total)', 70, 100, ['Smelting + Smithing']),
        new SkillItem('Bane Bar', 77, 50, ['Smelting']),
        new SkillItem('Bane (Smithing)', 80, 62.5, ['Smithing']),
        new SkillItem('Bane (Total)', 80, 112.5, ['Smelting + Smithing']),
        new SkillItem('Rune Bar', 85, 50, ['Smelting']),
        new SkillItem('Rune (Smithing)', 85, 75, ['Smithing']),
        new SkillItem('Rune (Total)', 85, 125, ['Smelting + Smithing']),
        // Artisans Workshop
        // Armour
        new SkillItem('Burial Armour - Iron I', 30, 111.1, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Iron II', 30, 222.2, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Iron III', 30, 264, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Steel I', 45, 144.1, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Steel II', 45, 278.3, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Steel III', 45, 389.4, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Mithril I', 60, 180.4, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Mithril II', 60, 347.6, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Mithril III', 60, 347.6, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Adamant I', 70, 305.8, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Adamant II', 70, 500.5, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Adamant III', 70, 624.8, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Rune I', 90, 555.5, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Rune II', 90, 694.1, ['Artisans Workshop']),
        new SkillItem('Burial Armour - Rune III', 90, 833.8, ['Artisans Workshop']),
        // Swords
        new SkillItem('Ceremonial Sword - Iron IV', 70, 3242, ['Artisans Workshop']),
        new SkillItem('Ceremonial Sword - Steel IV', 75, 4538, ['Artisans Workshop']),
        new SkillItem('Ceremonial Sword - Mithril IV', 80, 5446, ['Artisans Workshop']),
        new SkillItem('Ceremonial Sword - Adamant IV', 85, 6873, ['Artisans Workshop']),
        new SkillItem('Ceremonial Sword - Rune IV', 90, 8558, ['Artisans Workshop']),
        // Spear/Hasta
        new SkillItem('Bronze Spear/Hasta', 5, 25, ['Spears/Hastae']),
        new SkillItem('Bronze Spear/Hasta + Smelting', 5, 31.5, ['Spears/Hastae']),
        new SkillItem('Iron Spear/Hasta', 20, 50, ['Spears/Hastae']),
        new SkillItem('Iron Spear/Hasta + Smelting', 20, 62.5, ['Spears/Hastae']),
        new SkillItem('Steel Spear/Hasta', 35, 75, ['Spears/Hastae']),
        new SkillItem('Steel Spear/Hasta + Smelting', 35, 92.5, ['Spears/Hastae']),
        new SkillItem('Mithril Spear/Hasta', 55, 100, ['Spears/Hastae']),
        new SkillItem('Mithril Spear/Hasta + Smelting', 55, 130, ['Spears/Hastae']),
        new SkillItem('Adamant Spear/Hasta', 75, 125, ['Spears/Hastae']),
        new SkillItem('Adamant Spears/Hasta + Smelting', 75, 162.5, ['Spears/Hastae']),
        new SkillItem('Rune Spear/Hasta', 90, 150, ['Spears/Hastae']),
        new SkillItem('Rune Spear/Hasta + Smelting', 90, 200, ['Spears/Hastae']),
    ]
};
