skill_info[23] = {
    name: 'Summoning',
    categories: {
        title: 'Category',
        values: ['Gold Charm', 'Green Charm', 'Crimson Charm', 'Blue Charm']
    },
    items: [
        new SkillItem('Spirit Wolf<br/>(Wolf Bones, Gold Charm, 7 Shards)', 1, 4.8, ['Gold Charm']),
        new SkillItem('Dreadfowl<br/>(Raw Chicken, Gold Charm, 8 Shards)', 4, 9.3, ['Gold Charm']),
        new SkillItem('Spirit Spider<br/>(Spider Carcass, Gold Charm, 8 Shards)', 10, 12.6, ['Gold Charm']),
        new SkillItem('Thorny Snail<br/>(Raw Thin Snail, Gold Charm, 9 Shards)', 13, 12.6, ['Gold Charm']),
        new SkillItem('Granite Crab<br/>(Iron Ore, Gold Charm, 9 Shards)', 16, 21.6, ['Gold Charm']),
        new SkillItem('Mosquito<br/>(Proboscis, Gold Charm, 1 Shard)', 17, 46.5, ['Gold Charm']),
        new SkillItem('Desert Wyrm<br/>(Bucket of Sand, Green Charm, 45 Shards)', 18, 31.2, ['Green Charm']),
        new SkillItem('Spirit Scorpion<br/>(Bronze Claw, Crimson Charm, 57 Shards)', 19, 83.2, ['Crimson Charm']),
        new SkillItem('Spirit Tz-Kih<br/>(Obsidian Charm, Crimson Charm, 64 Shards)', 22, 96.8, ['Crimson Charm']),
        new SkillItem('Albino Rat<br/>(Raw Rat Meat, Blue Charm, 75 Shards)', 23, 202.4, ['Blue Charm']),
        new SkillItem('Spirit Kalphite<br/>(Potato Cactus, Blue Charm, 51 Shards)', 25, 220, ['Blue Charm']),
        new SkillItem('Compost Mound<br/>(Compost, Green Charm, 47 Shards)', 28, 49.8, ['Green Charm']),
        new SkillItem('Giant Chinchompa<br/>(Chinchompa, Blue Charm, 84 Shards)', 29, 255.2, ['Blue Charm']),
        new SkillItem('Vampire Bat<br/>(Vampyre Dust, Crimson Charm, 81 Shards)', 31, 136, ['Crimson Charm']),
        new SkillItem('Honey Badger<br/>(Honeycomb, Crimson Charm, 84 Shards)', 32, 140.8, ['Crimson Charm']),
        new SkillItem('Beaver<br/>(Willow Logs, Green Charm, 72 shards)', 33, 57.6, ['Green Charm']),
        new SkillItem('Void Ravager<br/>(Ravager Charm, Green Charm, 74 Shards)', 34, 59.6, ['Green Charm']),
        new SkillItem('Void Shifter<br/>(Shift Charm, Blue Charm, 74 Shards)', 34, 59.6, ['Blue Charm']),
        new SkillItem('Void Spinner<br/>(Spinner Charm, Blue Charm, 74 Shards)', 34, 59.6, ['Blue Charm']),
        new SkillItem('Void Torcher<br/>(Torcher Charm, Blue Charm, 74 Shards)', 34, 59.6, ['Blue Charm']),
        new SkillItem('Bronze Minotaur<br/>(Bronze Bar, Blue Charm, 102 Shards)', 36, 316.8, ['Blue Charm']),
        new SkillItem('Bull Ant<br/>(Marigolds, Gold Charm, 11 Shards)', 40, 52.8, ['Gold Charm']),
        new SkillItem('Macaw<br/>(Clean Guam, Green Charm, 78 Shards)', 41, 72.4, ['Green Charm']),
        new SkillItem('Evil Turnip<br/>(Carvedl Evil Turnip, Crimson Charm, 104 Shards)', 42, 184.8, ['Crimson Charm']),
        new SkillItem('Spirit Cockatrice<br/>(Cockatrice Egg, Green Charm, 88 Shards)', 43, 75.2, ['Green Charm']),
        new SkillItem('Iron Minotaur<br/>(Iron Bar, Blue Charm, 125 Shards)', 46, 404.8, ['Blue Charm']),
        new SkillItem('Pyrelord<br/>(Tinderbox, Crimson Charm, 111 Shards)', 46, 202.4, ['Crimson Charm']),
        new SkillItem('Magpie<br/>(Gold Ring, Green Charm, 88 Shards)', 47, 83.2, ['Green Charm']),
        new SkillItem('Bloated Leech<br/>(Raw Beef, Crimson Charm, 117 Shards)', 49, 215.2, ['Crimson Charm']),
        new SkillItem('Spirit Terrorbird<br/>(Raw Bird Meat, Gold Charm, 12 Shards)', 52, 68.4, ['Gold Charm']),
        new SkillItem('Abyssal Parasite<br/>(Abyssal Charm, Green Charm, 106 Shards)', 54, 94.8, ['Green Charm']),
        new SkillItem('Spirit Jelly<br/>(Jug of Water, Blue Charm, 151 Shards)', 55, 484, ['Blue Charm']),
        new SkillItem('Ibis<br/>(Harpoon, Green Charm, 109 Shards)', 56, 98.8, ['Green Charm']),
        new SkillItem('Steel Minotaur<br/>(Steel Bar, Blue Charm, 141 Shards)', 56, 492.8, ['Blue Charm']),
        new SkillItem('Spirit Graahk<br/>(Graahk Fur, Blue Charm, 154 Shards)', 57, 501.6, ['Blue Charm']),
        new SkillItem('Spirit Kyatt<br/>(Kyatt Fur, Blue Charm, 153 Shards', 57, 501.6, ['Blue Charm']),
        new SkillItem('Spirit Larupia<br/>(Larupia Fur, Blue Charm, 155 Shards', 57, 501.6, ['Blue Charm']),
        new SkillItem('Karamthulhu Overlord<br/>(Empty Fishbowl, Blue Charm, 144 Shards)', 58, 510.4, ['Blue Charm']),
        new SkillItem('Smoke Devil<br/>(Goat Horn Dust, Crimson Charm, 141 Shards)', 61, 268, ['Crimson Charm']),
        new SkillItem('Abyssal Luker<br/>(Abyssal Charm, Green Charm, 119 Shards)', 62, 109.6, ['Green Charm']),
        new SkillItem('Spirit Cobra<br/>(Snake Hide, Crimson Charm, 116 Shards)', 63, 276.8, ['Crimson Charm']),
        new SkillItem('Stranger Plant<br/>(Bagged Plant 1, Crimson Charm, 128 Shards)', 64, 281.6, ['Crimson Charm']),
        new SkillItem('Barker Toad<br/>(Swamp Toad, Gold Charm, 11 Shards)', 66, 87, ['Gold Charm']),
        new SkillItem('Blue Minotaur<br/>(Mithril Bar, Blue Charm, 152 Shards)', 66, 580.8, ['Blue Charm']),
        new SkillItem('War Tortoise<br/>(Tortoise Shell, Gold Charm, 1 Shard)', 67, 58.6, ['Gold Charm']),
        new SkillItem('Bunyip<br/>(Raw Shark, Green Charm, 110 Shards)', 68, 119.2, ['Green Charm']),
        new SkillItem('Fruit Bat<br/>(Banana, Green Charm, 130 Shards)', 69, 121.2, ['Green Charm']),
        new SkillItem('Ravenous Locust<br/>(Pot of Flour, Crimson Charm, 79 Shards)', 70, 132, ['Green Charm']),
        new SkillItem('Arctic Bear<br/>(Polar Kebbit Fur, Gold Charm, 14 Shards)', 71, 93.2, ['Gold Charm']),
        new SkillItem('Phoenix<br/>(Phoenix Quill, Crimson Charm, 165 Shards)', 72, 302, ['Crimson Charm']),
        new SkillItem('Obsidian Golem<br/>(Obsidian Charm, Blue Charm, 195 Shards)', 73, 642.4, ['Blue Charm']),
        new SkillItem('Granite Lobster<br/>(Granite, Crimson Charm, 166 Shards)', 74, 325.6, ['Crimson Charm']),
        new SkillItem('Praying Mantis<br/>(Flowers, Crimson Charm, 168 Shards)', 75, 329.6, ['Crimson Charm']),
        new SkillItem('Adamant Minotaur<br/>(Adamant Bar, Blue Charm, 144 Shards)', 76, 668.8, ['Blue Charm']),
        new SkillItem('Forge Regent<br/>(Ruby Harvest, Green Charm, 141 Shards)', 76, 134, ['Green Charm']),
        new SkillItem('Talon Beast<br/>(Talon Beast Charm, Crimson Charm, 174 Shards)', 77, 1015.2, ['Crimson Charm']),
        new SkillItem('Giant Ent<br/>(Willow Branch, Green Charm, 124 Shards)', 78, 136.8, ['Green Charm']),
        new SkillItem('Fire Titan<br/>(Fire Talisman, Blue Charm, 198 Shards)', 79,  695.2, ['Blue Charm']),
        new SkillItem('Ice Titan<br/>(Air + Water Talisman, Blue Charm, 198 Shards)', 79, 695.2, ['Blue Charm']),
        new SkillItem('Moss Talisman<br/>(Earth Talisman, Blue Charm, 202 Shards)', 79, 695.2, ['Blue Charm']),
        new SkillItem('Hydra<br/>(Water Orb, Green Charm, 128 Shards)', 80, 140.8, ['Green Charm']),
        new SkillItem('Lava Titan<br/>(Obsidian Charm, Blue Charm, 219 Shards)', 83, 730.4, ['Blue Charm']),
        new SkillItem('Spirit Daggnnoth<br/>(Dagannoth Hide, Crimson Charm, 1 Shard)', 83, 364.8, ['Crimson Charm']),
        new SkillItem('Swamp Titan<br/>(Swamp Lizard, Crimson Charm, 150 Shards)', 85, 373.6, ['Crimson Charm']),
        new SkillItem('Rune Minotaur<br/>(Rune Bar, Blue Charm, 1 Shard)', 86, 756.8, ['Blue Charm']),
        new SkillItem('Unicorn Stallion<br/>(Unicorn Horn, Green Charm, 140 Shards)', 88, 154.4, ['Green Charm']),
        new SkillItem('Geyser Titan<br/>(Water Talisman, Blue Charm, 222 Shards)', 89, 783.2, ['Blue Charm']),
        new SkillItem('Wolpertinger<br/>(Raw Rabbit + Wolf Bones, Crimson Charm, 203 Shards)', 92, 404.8, ['Crimson Charm']),
        new SkillItem('Abyssal Titan<br/>(Abyssal Charm, Green Charm, 113 Shards)', 93, 163.2, ['Green Charm']),
        new SkillItem('Iron Titan<br/>(Iron Platebody, Crimson Charm, 198 Shards)', 95, 417.6, ['Crimson Charm']),
        new SkillItem('Pack Yak<br/>(Yak-hide, Crimson Charm, 211 Shards)', 96, 422.4, ['Crimson Charm']),
        new SkillItem('Steel Titan(Steel Platebody, Crimson Charm, 178 Shards)', 99, 435.2, ['Crimson Charm']),
    ]
};
