skill_info[17] = {
    name: 'Thieving',
    categories: {
        title: 'Category',
        values: ['Pickpocketing', 'Stalls', 'Chests', 'Sorceress\'s Garden']
    },
    items: [
        new SkillItem('Man/Woman', 1, 8, ['Pickpocketing']),
        new SkillItem('Winter Sq\'irk Juice', 1, 350, ['Sorceress\'s Garden']),
        new SkillItem('Vegetable Stall', 2, 10, ['Stalls']),
        new SkillItem('Barker\'s Stall', 5, 16, ['Stalls']),
        new SkillItem('Crafting Stall', 5, 16, ['Stalls']),
        new SkillItem('General Stall', 5, 16, ['Stalls']),
        new SkillItem('Monkey Food Stall', 5, 16, ['Stalls']),
        new SkillItem('Tea Stall', 5, 16, ['Stalls']),
        new SkillItem('Farmer', 10, 14.5, ['Pickpocketing']),
        new SkillItem('10 Coins Chest', 13, 7.5, ['Chests']),
        new SkillItem('Rock Cake Stall', 15, 10, ['Stalls']),
        new SkillItem('Female HAM Member', 15, 18.5, ['Pickpocketing']),
        new SkillItem('Male HAM Member', 20, 22.2, ['Pickpocketing']),
        new SkillItem('Silk Stall', 20, 24, ['Stalls']),
        new SkillItem('Wine Stall', 22, 27, ['Stalls']),
        new SkillItem('HAM Guard', 23, 22.2, ['Pickpocketing']),
        new SkillItem('Warrior', 25, 26, ['Pickpocketing']),
        new SkillItem('Spring Sq\'irk Juice', 25, 1350, ['Sorceress\'s Garden']),
        new SkillItem('Seed Stall', 27, 10, ['Stalls']),
        new SkillItem('Nature Rune Chest', 28, 25, ['Chests']),
        new SkillItem('Rogue', 32, 36.5, ['Pickpocketing']),
        new SkillItem('Fur Stall', 35, 36, ['Stalls']),
        new SkillItem('Cave Goblin', 36, 40, ['Pickpocketing']),
        new SkillItem('Master Farmer', 38, 43, ['Pickpocketing']),
        new SkillItem('Guard', 40, 46.8, ['Pickpocketing']),
        new SkillItem('Fish Stall', 42, 42, ['Stalls']),
        new SkillItem('50 Coins Chest', 43, 125, ['Chests']),
        new SkillItem('Bearded Pollnivian Bandit', 45, 65, ['Pickpocketing']),
        new SkillItem('Fremennik', 45, 65, ['Pickpocketing']),
        new SkillItem('Autumn Sq\'ik Juice', 45, 2350, ['Sorceress\'s Garden']),
        new SkillItem('Steel Arrowheads Chest', 47, 150, ['Chests']),
        new SkillItem('Crossbow Stall', 49, 52, ['Stalls']),
        new SkillItem('Silver Stall', 50, 54, ['Stalls']),
        new SkillItem('Wall Safe', 50, 70, ['Chests']),
        new SkillItem('Dorgesh-Kaan (Low)', 52, 200, ['Chests']),
        new SkillItem('Desert Bandit', 53, 79.4, ['Pickpocketing']),
        new SkillItem('Knight', 55, 84.3, ['Pickpocketing']),
        new SkillItem('Pollnivian Bandit', 55, 84.3, ['Pickpocketing']),
        new SkillItem('Blood Rune Chest', 59, 288, ['Chests']),
        new SkillItem('Spice Stall', 65, 81.3, ['Stalls']),
        new SkillItem('Magic Stall', 65, 100, ['Stalls']),
        new SkillItem('Menaphite Thug', 65, 137.5, ['Pickpocketing']),
        new SkillItem('Yanille Watchman', 65, 137.5, ['Pickpocketing']),
        new SkillItem('Scimitar Stall', 65, 160, ['Stalls']),
        new SkillItem('Summer Sq\'irk Juice', 65, 3000, ['Sorceress\'s Garden']),
        new SkillItem('Paladin', 70, 151.8, ['Pickpocketing']),
        new SkillItem('Ardougne Castle Chest', 72, 500, ['Chests']),
        new SkillItem('Gem Stall', 75, 160, ['Stalls']),
        new SkillItem('Gnome', 75, 198.3, ['Pickpocketing']),
        new SkillItem('Dorgesh-Kaan (High)', 78, 650, ['Chests']),
        new SkillItem('Hero', 80, 273.3, ['Pickpocketing']),
        new SkillItem('Elf', 85, 353.3, ['Pickpocketing']),
        new SkillItem('Dwarf Trader', 90, 556.5, ['Pickpocketing']),
    ]
};
